### ISSUE TITLE
Excuse me ，There is a problem here.

### ISSUE THREAD

**Issue by alpha51870** [semontesdeoca/MNPR#13]
maya2018.3
Error: AttributeError: file D:\Documents\maya\MNPR-master\scripts\mnpr_info.py line 39: 'module' object has no attribute 'mnpr' #

**Comment by semontesdeoca** [comment]
I need more information to troubleshoot this...
However, it seems like the plugin could not be successfully loaded.

**Comment by alpha51870** [comment]
First of all, thank you for your reply, then how can I give you more information or what information?

**Comment by alpha51870** [comment]
/////////////////////////////////////////////////////////////////////////////////////
//
// File: install.mel
// Description:
//      Installation script for MNPR
// Author: Santiago E. Montesdeoca
// Website: http://artineering.io
// Contributor: Pierre Benard
//
// Instructions:
//      Drag and drop this file into the Maya viewport to install dependencies
//
/////////////////////////////////////////////////////////////////////////////////////
{ // avoid global namespace clashing

  // add scripts path to PYTHONPATH
  string $fileDir = `installScriptLocation`;
  python ("import sys");
  string $pyPaths[] = python ("sys.path");
  int $times = stringArrayCount ($fileDir, $pyPaths);
  string $scriptsDir = $fileDir + "scripts/";
  if ( stringArrayCount ($scriptsDir, $pyPaths) == 0 ) {
      //print "Adding current path to PYTHONPATH";
      python ("sys.path.insert(0, '" + $scriptsDir + "')") ;
  }

  python ("import mnpr_setup");
  python ("reload(mnpr_setup)");
  python ("mnpr_setup.run('" + $fileDir + "')");

  global proc string installScriptLocation () {
      string $whatIs=`whatIs installScriptLocation`;
      // $whatIs "Mel procedure found in: C:/Users/...."
      string $fullPath=`substring $whatIs 25 999`;
      string $buffer[];
      int $numTok=`tokenize $fullPath "/" $buffer`;
      int $numLetters=size($fullPath);
      int $numLettersLastFolder=size($buffer[$numTok-1]);
      string $scriptLocation=`substring $fullPath 1 ($numLetters-$numLettersLastFolder)`;
      return $scriptLocation;
  }
};
# Error: line 27: ImportError: file <maya console> line 1: No module named mnpr_setup #

**Comment by alpha51870** [comment]
I updated maya2018.4 and MNPR
Can be used
Thank you

**Comment by semontesdeoca** [comment]
I'm happy to hear that, enjoy!

**Comment by JexD** [comment]
hello, i have the same trouble, any way to make it work with 2018.3, i can't change version during project
