### ISSUE TITLE
How to Render EXR with AOV 

### ISSUE THREAD

**Issue by jmGaoshan** [semontesdeoca/MNPR#16]
Hi,

Just discover and try your awesome software!

 but i dont figure out to render an exr file with what i see in Maya, actually it renders only an EXR with 'colorTarget' though the exr is quite heavy i dont see any other AOV inside (i used Nuke to check)

Also, and as a second request how to render sequence of images, like batch rendering ?

Thank you!

Jean-marc

**Comment by semontesdeoca** [comment]
Hi Jean-marc, it sounds to me that you are after [MNPRX](https://artineering.io/projects/MNPRX/) instead. You can batch export EXR sequences and all AOVs.
