### ISSUE TITLE
// Error: file: C:/Program Files/Autodesk/Maya2018/scripts/others/pluginWin.mel line 290: initializePlugin function failed (MNPR)

### ISSUE THREAD

**Issue by Z0hc** [semontesdeoca/MNPR#2]
![2fc4q hyl mdgkae ulev9](https://user-images.githubusercontent.com/40259137/41395238-8948820e-6fdf-11e8-954b-c067285b02ba.png)

**Comment by semontesdeoca** [comment]
what operating system and what version of Maya are you using?

**Comment by Z0hc** [comment]
2018

**Comment by Z0hc** [comment]
![jb2kj _t 14 hjyg ssb g](https://user-images.githubusercontent.com/40259137/41395490-7a326784-6fe0-11e8-9bb1-5ed542cd1808.png)

**Comment by semontesdeoca** [comment]
Which version of Maya 2018?
sorry I can't understand chinese

**Comment by Z0hc** [comment]
yes

**Comment by Z0hc** [comment]
![u 3uw25a ibeef 0hmend1](https://user-images.githubusercontent.com/40259137/41395656-14d07d30-6fe1-11e8-9417-3b60a6c29222.png)
![8uzamz_rc kv zm38 o 0rx](https://user-images.githubusercontent.com/40259137/41395657-14f87dee-6fe1-11e8-9af2-56119f27eb0c.png)

**Comment by semontesdeoca** [comment]
I can't replicate this on Windows 10, Maya 2018.3
What OS are you using and which version of Maya 2018 do you have?

To check your version of Maya: _Help->About Maya_

**Comment by xiesi88** [comment]
@Z0hc 你怎么安装的？我是手动安装到Maya2017中文版上的

**Comment by Z0hc** [comment]
这有没有可能是我操作不当，不过我确实是按照你教授的反法，还是说是我电脑的问题
Is it possible that I did not operate properly, but I did follow your professor's anti - law or my computer problem?
我英语也不太懂
I don't understand English too much
这是翻译机
This is the translation machine

**Comment by Z0hc** [comment]
Can you teach me  @xiesi88

**Comment by xiesi88** [comment]
@Z0hc 可以，建议你用第二种安装方式再试一次。

**Comment by Z0hc** [comment]
Thank you

**Comment by xiesi88** [comment]
@Z0hc You got it.

**Comment by Z0hc** [comment]
No, I'm still trying.

**Comment by xiesi88** [comment]
@Z0hc 严格按照第二个解决方案试一下。

**Comment by Z0hc** [comment]
@xiesi88 
方法2，
我有点操作不来
Method 2,

I can't do a bit of it

**Comment by Z0hc** [comment]
Do not understand the operation method

**Comment by Z0hc** [comment]
@xiesi88 I've already solved it
I downloaded a problematic installation package, so I couldn't install it.
Thanks for your help
