### ISSUE TITLE
New scenes don't show shadow

### ISSUE THREAD

**Issue by lamdrea** [semontesdeoca/MNPR#21]
When viewing the sample test scenes, there are object shadows visible. Adding new objects and new materials to these scenes work fine. 

However, whenever I make my own scene from scratch, any materials made do not show shadows, even with the default test sphere. The attached image shows the default test sphere and a plane (same material for both).
![noshadows](https://user-images.githubusercontent.com/13225578/55338191-2414f600-546e-11e9-8802-041ba15eeec5.jpg)

**Comment by semontesdeoca** [comment]
You need to enable them in the viewport
![image](https://user-images.githubusercontent.com/1998692/55338399-f301e900-54a0-11e9-8c90-e538b729098b.png)

**Comment by lamdrea** [comment]
Ah! Sorry for missing that, thank you!!
