### ISSUE TITLE
How to render EXR with AOV for an animation (on maya MNPR) ?

### ISSUE THREAD

**Issue by Lisa-22** [semontesdeoca/MNPR#22]
Hi ! 

Just discover and try your awesome software (Thanks for this wonderful software) !

I'm a student in animation and I would like to know how to render EXR with AOV for an animation on maya MNPR (how to render sequence of images) ? Is it possible because I would like to use this render for my degree's project ? 

Thanks !

**Comment by semontesdeoca** [comment]
Hi Lisa, it sounds to me that you are after [MNPRX](https://artineering.io/projects/MNPRX/) instead. You can export EXR sequences will all AOVs there.
