### ISSUE TITLE
Installation Problem - No module named mnpr_runner

### ISSUE THREAD

**Issue by MaheshinderSingh** [semontesdeoca/MNPR#24]
Hi! I've been running into an issue trying to install MNPR. I drag it into my viewport which worked perfectly. I restarted maya and saw the MNPR shelf added to my shelf library. I click on any of the buttons on the shelf and I'm met with :

import mnpr_runner
mnpr_runner.testScene()
# Error: ImportError: file <maya console> line 1: No module named mnpr_runner #

I was wondering what I could do to solve this problem, I'm really looking forward to using this for my project. Thank you!

**Comment by MaheshinderSingh** [comment]
Got some help from my teacher and figured it out. Stupid on my part, I needed to install the files into my maya scripts folder

**Comment by semontesdeoca** [comment]
You should **NOT** put the files in the script folder, this is what messed up the loading of presets issue that [you have been having](https://github.com/semontesdeoca/MNPR/issues/25)

**Comment by semontesdeoca** [comment]
I'll need the following to troubleshoot this:

1. What version of Maya are you using?
2. What OS are you using?
3. What are the contents of your _Maya.env_ (documents/mayaversion/Maya.env) file?

**Comment by MaheshinderSingh** [comment]
1. Using Maya 2018.5
2. Using Windows 7
3. Here is whats in my Maya.env file verbatim

MAYA_SHELF_PATH=C:\Users\3d136maheshi\Desktop\MNPR\shelves;
MNPR_PATH=C:\Users\3d136maheshi\Desktop\MNPR;
MAYA_PLUG_IN_PATH=C:\Users\3d136maheshi\Desktop\MNPR\plugins\2018\win;
PYTHONPATH=C:\Users\3d136maheshi\Desktop\MNPR\scripts;
MAYA_SCRIPT_PATH=C:\Users\3d136maheshi\Desktop\MNPR\scripts;
MAYA_VP2_USE_GPU_MAX_TARGET_SIZE=1;
XBMLANGPATH=C:\Users\3d136maheshi\Desktop\MNPR\icons;

**Comment by semontesdeoca** [comment]
That seems odd, everything seems in order to me..
can you run the following python command for me?

`import mnpr_system`

please let me know if that comes through

**Comment by MaheshinderSingh** [comment]
I'm prompted with this message

import mnpr_system
# Error: ImportError: file <maya console> line 1: No module named mnpr_system #

**Comment by semontesdeoca** [comment]
Sorry about that, there seems to be something wrong with your computer or Maya installation.
The PYTHONPATH in the Maya.env file is the one that specifies where the scripts should be found and that seems to be set correctly (please check if the _mnpr_system_ file is in there).

Other than that, you could try putting all the contents of the MNPR system inside your _Documents/maya/2018_ folder and installing it from there. I've personally never tried this way before as its cluttered, but its worth a try. 

I can't help much more remotely from here.

**Comment by MaheshinderSingh** [comment]
Yeah putting all the contents of the MNPR folder in the maya 2018 folder seemed to work. Thank you for your help :)
