### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by greg-garay** [semontesdeoca/MNPR#27]
Dragging and dropping in the view port does not work.

ValueError: file C:/Users/garayg/Downloads/scripts/coopLib.py line 80: could not convert string to float: Autodesk #

**Comment by semontesdeoca** [comment]
Hi Greg,

please make sure to use [MNPRX](https://artineering.io/projects/MNPRX/) instead of MNPR, as MNPR is not maintained anymore.

Cheers!
