### ISSUE TITLE
shadow show in the view is wrong

### ISSUE THREAD

**Issue by michaelzhou8888** [semontesdeoca/MNPR#28]
[
![image](https://user-images.githubusercontent.com/58095782/69471071-75477080-0dd6-11ea-8fb1-6e046b462a03.png)
](url)

**Comment by semontesdeoca** [comment]
Hi Michael,

please make sure to use [MNPRX](https://artineering.io/projects/MNPRX/) instead of MNPR, as MNPR is not maintained anymore.

Cheers!

**Comment by michaelzhou8888** [comment]
oh, my gosh
