### ISSUE TITLE
Maya 2019 error

### ISSUE THREAD

**Issue by halfGuardian** [semontesdeoca/MNPR#30]
# Error: RuntimeError: file D:\maya\MNPR\scripts\mnpr_info.py line 48: Maya can't find the MNPR plugin or the version of the plugin is not compatible with this version of Maya (see FAQ for more information) # 

Does Maya 2019 not support the plugin??

**Comment by semontesdeoca** [comment]
MNPR was compiled only until Maya 2018.
You can compile it yourself for Maya 2019 or switch to [MNPRX ](https://artineering.io/software/MNPRX/) which is the maintained and production-ready version.
