### ISSUE TITLE
C:\...\maya\MNPR-1.0.2\MNPR-1.0.2\shaders>REM Contributor: Santiago Montesdeoca fxc.exe not found on this computer

### ISSUE THREAD

**Issue by halfGuardian** [semontesdeoca/MNPR#31]
I just noticed you setup CMake already to recompile - I'm trying to recompile for 2019 but I get this error.  I've run as admin etc and still the same error.  Any suggestions?

**Comment by semontesdeoca** [comment]
This means that the shader compiler couldn't be found in your computer. You'll have to modify the [HLSL compiler ](https://github.com/semontesdeoca/MNPR/blob/master/shaders/_compileHLSL.bat) batch script and run the compilation again.

I do recommend to use MNPRX instead though, as MNPR is more than two years behind in development and just a research prototype.
