### ISSUE TITLE
MNPR for Maya 2019

### ISSUE THREAD

**Issue by kentseki** [semontesdeoca/MNPR#32]
Hi there,
Is there version of MNPR compiled for MAYA 2019? If not, is there a way to compile it other than using CMake?

Thanks,

Kent

**Comment by semontesdeoca** [comment]
Hi @kentseki,
not of MNPR, but you can use [MNPRX](https://artineering.io/software/MNPRX/) which works with Maya 2018-2022 and is production ready.
Cheers!
