### ISSUE TITLE
Plugin loads with no errors. But the viewport renderer shows everything black

### ISSUE THREAD

**Issue by charliewales** [semontesdeoca/MNPR#7]
Hi, I have installed MNPR as a module, all looks good, no error that I see. But the renderer does not work as expected. I attach a screenshot, the test scene is all black. I can see the wireframe though. It seems as if the plugin cannot find the shaders. I also tried the install.mel installation but the same, all black. If I orbit the camera the grid acts as a Spyrograph. Those weird lines in the image are the grid.
Thanks for sharing. A pasarlo bien.

Windows 10 x64 1803, Maya 2017 Update 5.

![imagen](https://user-images.githubusercontent.com/2865181/41620910-6a6b04a8-740b-11e8-81b7-aebb6184408a.png)

**Comment by charliewales** [comment]
I tried again with fresh maya prefs and via install.mel and it works. There must be something in my prefs that messes the plugin. If I manage to find the source of the error I'll post it here. Thanks

![imagen](https://user-images.githubusercontent.com/2865181/41674337-ff957f18-74bf-11e8-8171-1bc1054109aa.png)

**Comment by charliewales** [comment]
I tried again to install it as a module and I think. I narrowed down the error to the fact that I intentionally renamed the plugin folder to plug-ins to follow Maya module default structure. Once I renamed the plug-ins folder to plugins it worked. I guess some harcoded code expects the windows mll to be inside the plugins folder. Cheers

**Comment by semontesdeoca** [comment]
Yeah, you shouldn't rename the folders inside of the MNPR folder...
Actually, you shouldn't change the name of folders in any software without expecting things to break! =)

**Comment by craGato** [comment]
You are right I guess. But this behaviour does not follow the maya paradigm. I mean, if Maya finds the plugin that is needed for some tool or script or whatever in its MAYA_PLUGIN_PATH it should work, no matter where the file resides in disk and the location should not matter. That's why at first I did not find the culprit of the error because I was following the "Maya way". The plugin was found by Maya and it also loaded with no errors. Anyway, thanks for sharing this it looks very nice. Cheers

**Comment by semontesdeoca** [comment]
Well... I'm sure we can all agree that this is not a normal Maya plugin =)
There are countless other custom files (scripts, shaders, presets, icons) that the plugin needs to be aware of, so just loading the plugin won't work.
