### ISSUE TITLE
Alpha outputs are unusable when antialiasing is on

### ISSUE THREAD

**Issue by GordonPinkerton** [semontesdeoca/MNPR#8]
![alphaissues](https://user-images.githubusercontent.com/37560097/41626191-50199d48-73d0-11e8-88cc-f01e49ec6610.JPG)

Alphas contain "holes" making it impossible to do any sort of compositing with output frames

**Comment by semontesdeoca** [comment]
thanks for bringing this up. For now, just turn off the anti-aliasing to get rid of these holes.
